### ISSUE TITLE
Pull event type from events table and display on update message

### ISSUE THREAD

**Issue by csyers** [timzchang/cse30246_project#3]

**Comment by csyers** [comment]
Use get_event_type.php to do so. Returns a message with the event type on a given day...

FORMAT: POST with date in form YYYY-MM-DD (standard mySQL)

**Comment by timzchang** [comment]
Is this referring to the update-issue dialogs in calendar.html and view.html?

**Comment by csyers** [comment]
Unsure what this is about. We can probably just close it

**Comment by csyers** [comment]
Maybe something to do with the calendar? But yeah I forget. Do we ever use event_type.php?

**Comment by timzchang** [comment]
I don't know, but I think I'm going to take it as changing the update form

**Comment by csyers** [comment]
Oh I remember. We don't want to be able to update the type of event, but it would be cool if the update form said the type of date that it was editing

**Comment by csyers** [comment]
Remove Event Type field and instead, fill a text field with the event type for the event on the date on the form.

**Comment by timzchang** [comment]
yup that's what I was talking about

**Comment by csyers** [comment]
awesome

**Comment by timzchang** [comment]
Dunno if this is possible atm. Am looking around.

**Comment by csyers** [comment]
If it isn't, no problem. I still don't think you should be able to change the event type from this interface, as this would require changing the event table as well as attendance_issues
